package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorModule.idl
* Monday, 29 May, 2023 11:01:05 AM IST
*/

public interface CalculatorOperations 
{
  int add (int x, int y);
  int sub (int x, int y);
  int div (int x, int y);
  int mul (int x, int y);
} // interface CalculatorOperations
