package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorModule.idl
* Sunday, 28 May, 2023 10:41:21 PM IST
*/

public interface CalculatorOperations 
{
  int add (int x, int y);
} // interface CalculatorOperations
